[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
