export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
    generator: 'v0.app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}


import './globals.css'